describe("Contact",()=>{
    it("CreateContactWithOrganization",()=>{
        cy.visit("http://localhost:8888/")
        cy.get('.inputs > :nth-child(2) > input').type("admin")
        cy.get(':nth-child(5) > input').type("admin")
        cy.get('#submitButton').click()
        cy.contains('Contacts').click()
        cy.get(':nth-child(1) > table > tbody > tr > [style="padding-right:0px;padding-left:10px;"] > a > img').click()
        cy.get(':nth-child(4) > :nth-child(2) > .detailedViewTextBox').type("Adaam")
        cy.get(':nth-child(5) > :nth-child(2) > img').click()
        // cy.wait(4000)
        // cy.window()
        cy.get('[name="search_text"]').type("TestYantra")
    })
})